cmake_minimum_required(VERSION 3.31)
project(kissat C)

set(CMAKE_C_STANDARD 11)

include_directories(build)
include_directories(src)
include_directories(test)

add_executable(kissat
        build/build.h
        src/allocate.c
        src/allocate.h
        src/analyze.c
        src/analyze.h
        src/ands.c
        src/ands.h
        src/application.c
        src/application.h
        src/arena.c
        src/arena.h
        src/array.h
        src/assign.c
        src/assign.h
        src/attribute.h
        src/averages.c
        src/averages.h
        src/backbone.c
        src/backbone.h
        src/backtrack.c
        src/backtrack.h
        src/build.c
        src/bump.c
        src/bump.h
        src/check.c
        src/check.h
        src/classify.c
        src/classify.h
        src/clause.c
        src/clause.h
        src/clauseexport.c
        src/clauseexport.h
        src/clauseimport.h
        src/collect.c
        src/collect.h
        src/colors.c
        src/colors.h
        src/compact.c
        src/compact.h
        src/config.c
        src/config.h
        src/congruence.c
        src/congruence.h
        src/cover.h
        src/decide.c
        src/decide.h
        src/deduce.c
        src/deduce.h
        src/definition.c
        src/definition.h
        src/dense.c
        src/dense.h
        src/dump.c
        src/eliminate.c
        src/eliminate.h
        src/equivalences.c
        src/equivalences.h
        src/error.c
        src/error.h
        src/extend.c
        src/extend.h
        src/factor.c
        src/factor.h
        src/fastassign.h
        src/fastel.c
        src/fastel.h
        src/fifo.h
        src/file.c
        src/file.h
        src/flags.c
        src/flags.h
        src/format.c
        src/format.h
        src/forward.c
        src/forward.h
        src/frames.h
        src/gates.c
        src/gates.h
        src/handle.c
        src/handle.h
        src/heap.c
        src/heap.h
        src/ifthenelse.c
        src/ifthenelse.h
        src/import.c
        src/import.h
        src/inline.h
        src/inlineassign.h
        src/inlineframes.h
        src/inlineheap.h
        src/inlinequeue.h
        src/inlinevector.h
        src/internal.c
        src/internal.h
        src/keatures.h
        src/kimits.c
        src/kimits.h
        src/kissat.h
        src/kitten.c
        src/kitten.h
        src/krite.c
        src/krite.h
        src/learn.c
        src/learn.h
        src/literal.h
        src/logging.c
        src/logging.h
        src/lucky.c
        src/lucky.h
        src/main.c
        src/minimize.c
        src/minimize.h
        src/mode.c
        src/mode.h
        src/options.c
        src/options.h
        src/parse.c
        src/parse.h
        src/phases.c
        src/phases.h
        src/preprocess.c
        src/preprocess.h
        src/print.c
        src/print.h
        src/probe.c
        src/probe.h
        src/profile.c
        src/profile.h
        src/promote.c
        src/promote.h
        src/proof.c
        src/proof.h
        src/propbeyond.c
        src/propbeyond.h
        src/propdense.c
        src/propdense.h
        src/propinitially.c
        src/propinitially.h
        src/proplit.h
        src/proprobe.c
        src/proprobe.h
        src/propsearch.c
        src/propsearch.h
        src/queue.c
        src/queue.h
        src/random.h
        src/rank.h
        src/reduce.c
        src/reduce.h
        src/reference.h
        src/reluctant.c
        src/reluctant.h
        src/reorder.c
        src/reorder.h
        src/rephase.c
        src/rephase.h
        src/report.c
        src/report.h
        src/require.h
        src/resize.c
        src/resize.h
        src/resolve.c
        src/resolve.h
        src/resources.c
        src/resources.h
        src/restart.c
        src/restart.h
        src/search.c
        src/search.h
        src/shrink.c
        src/shrink.h
        src/smooth.c
        src/smooth.h
        src/sort.c
        src/sort.h
        src/stack.h
        src/statistics.c
        src/statistics.h
        src/strengthen.c
        src/strengthen.h
        src/substitute.c
        src/substitute.h
        src/sweep.c
        src/sweep.h
        src/terminate.c
        src/terminate.h
        src/tiers.c
        src/tiers.h
        src/trail.c
        src/trail.h
        src/transitive.c
        src/transitive.h
        src/utilities.c
        src/utilities.h
        src/value.h
        src/vector.c
        src/vector.h
        src/vivify.c
        src/vivify.h
        src/walk.c
        src/walk.h
        src/warmup.c
        src/warmup.h
        src/watch.c
        src/watch.h
        src/weaken.c
        src/weaken.h
        src/witness.c
        src/witness.h
        test/big/genbigand.c
        test/test.c
        test/test.h
        test/testadd.c
        test/testallocate.c
        test/testapplication.c
        test/testapplication.h
        test/testarena.c
        test/testarray.c
        test/testbump.c
        test/testceil.c
        test/testcnfs.h
        test/testcollect.c
        test/testconfig.c
        test/testcoverage.c
        test/testdivert.c
        test/testdivert.h
        test/testdump.c
        test/testendianness.c
        test/testerror.c
        test/testfifo.c
        test/testfile.c
        test/testformat.c
        test/testheap.c
        test/testinit.c
        test/testkitten.c
        test/testmain.c
        test/testmessages.c
        test/testmessages.h
        test/testoptions.c
        test/testparse.c
        test/testprove.c
        test/testqueue.c
        test/testrandom.c
        test/testrank.c
        test/testreferences.c
        test/testreluctant.c
        test/testscheduler.c
        test/testscheduler.h
        test/testsizes.c
        test/testsolve.c
        test/testsort.c
        test/teststack.c
        test/testterminate.c
        test/testusage.c
        test/testutilities.c
        test/testvector.c)
